# Generated by Django 6.0.2 on 2026-02-28 12:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilestoneTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.CharField(choices=[('UK', 'UK'), ('USA', 'USA'), ('AU', 'Australia'), ('ALL', 'All')], max_length=3)),
                ('order', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(max_length=60)),
                ('is_free', models.BooleanField(default=False)),
                ('required_docs', models.JSONField(default=list)),
                ('unlock_after', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocks', to='lanes.milestonetemplate')),
            ],
            options={
                'ordering': ['destination', 'order'],
                'unique_together': {('destination', 'order')},
            },
        ),
        migrations.CreateModel(
            name='CandidateMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('LOCKED', 'Locked'), ('IN_PROGRESS', 'In Progress'), ('PENDING_REVIEW', 'Pending Review'), ('COMPLETED', 'Completed')], default='LOCKED', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='accounts.candidateprofile')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lanes.milestonetemplate')),
            ],
            options={
                'unique_together': {('candidate', 'template')},
            },
        ),
    ]
