# Generated by Django 6.0.2 on 2026-03-01 06:57

import apps.referrals.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referral_code', models.CharField(default=apps.referrals.models.generate_referral_code, help_text='Unique code used in referral links.', max_length=12, unique=True)),
                ('commission_type', models.CharField(choices=[('FIXED', 'Fixed Amount (KSH)'), ('PERCENTAGE', 'Percentage of Payment')], default='FIXED', max_length=12)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=500.0, help_text='Fixed KSH amount or percentage (e.g. 500 or 10.00).', max_digits=10)),
                ('phone_number', models.CharField(blank=True, help_text='Phone number for M-Pesa payouts.', max_length=20)),
                ('total_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Affiliate',
                'verbose_name_plural': 'Affiliates',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('SIGNED_UP', 'Signed Up'), ('ACTIVE', 'Active (Profile Created)'), ('PAID', 'Has Made a Payment')], default='SIGNED_UP', max_length=12)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='referrals.affiliateprofile')),
                ('candidate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral', to='accounts.candidateprofile')),
                ('referred_user', models.OneToOneField(help_text='The user who signed up via referral link.', on_delete=django.db.models.deletion.CASCADE, related_name='referral_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral',
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PAID', 'Paid Out')], default='PENDING', max_length=12)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='payments.mpesatransaction')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='referrals.referral')),
            ],
            options={
                'verbose_name': 'Commission',
            },
        ),
    ]
