# Generated by Django 6.0.2 on 2026-02-28 12:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('MENTOR', 'UK Nursing Mentor'), ('THERAPIST', 'Psychotherapist'), ('ADMIN', 'Platform Administrator')], max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('can_verify_docs', models.BooleanField(default=False)),
                ('can_upload_content', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partner Profile',
            },
        ),
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.CharField(choices=[('UK', 'United Kingdom'), ('USA', 'United States'), ('AU', 'Australia')], max_length=3)),
                ('qualification', models.CharField(choices=[('DEGREE', 'Bachelor of Science in Nursing'), ('DIPLOMA', 'Diploma in Nursing')], max_length=10)),
                ('nck_number', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('status', models.CharField(choices=[('ONBOARDING', 'Onboarding'), ('ACTIVE', 'Active'), ('PLACEMENT_READY', 'Placement Ready'), ('PLACED', 'Placed')], default='ONBOARDING', max_length=20)),
                ('activation_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Candidate Profile',
                'indexes': [models.Index(fields=['destination', 'status'], name='accounts_ca_destina_cc68b9_idx')],
            },
        ),
    ]
