# Generated by Django 6.0.2 on 2026-06-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='destination',
            field=models.CharField(choices=[('UK', 'Orthopedic & Spine Care'), ('USA', 'Sports Rehabilitation'), ('AU', 'Neurological & Stroke Recovery')], max_length=3),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='nck_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Physiotherapy Council Registration Number'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='qualification',
            field=models.CharField(choices=[('DEGREE', 'Bachelor of Science in Physiotherapy'), ('DIPLOMA', 'Diploma in Physiotherapy')], max_length=10),
        ),
    ]
