# Generated by Django 6.0.2 on 2026-06-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='exam_type',
            field=models.CharField(choices=[('ORTHO', 'Orthopedic & Spine Care'), ('SPORTS', 'Sports & Active Rehab'), ('NEURO', 'Stroke & Neuro Care'), ('GENERAL', 'General Wellness & Prevention')], max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('CASE', 'Clinical Case Study')], max_length=5),
        ),
    ]
