# Generated by Django 6.0.2 on 2026-02-28 17:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationHighlight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country_name', models.CharField(max_length=100)),
                ('flag_emoji', models.CharField(help_text='e.g., 🇬🇧', max_length=10)),
                ('badge_text', models.CharField(help_text='e.g., CBT + NMC', max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('image', models.ImageField(help_text='High-res background image', upload_to='home/destinations/')),
                ('link_url', models.CharField(default='#', help_text='URL to redirect to (e.g. a local page slug)', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Destination Highlights',
                'ordering': ['order', 'country_name'],
            },
        ),
        migrations.CreateModel(
            name='PathwayHighlight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='e.g., Nursing in London', max_length=150)),
                ('subtitle', models.CharField(help_text='e.g., NHS Trusts & Private Care', max_length=150)),
                ('link_url', models.CharField(default='#', help_text='URL referencing the specific LocalPage', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Pathway Highlights',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('initials', models.CharField(help_text="e.g., 'MW' for Mary W.", max_length=5)),
                ('route_from', models.CharField(help_text="e.g., 'Nairobi'", max_length=100)),
                ('route_to', models.CharField(help_text="e.g., 'London'", max_length=100)),
                ('content', models.TextField(help_text='The testimonial quote.')),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='1 to 5 stars')),
                ('bg_color_class', models.CharField(default='bg-brand-100', help_text="Tailwind class like 'bg-brand-100' or 'bg-green-100'", max_length=50)),
                ('text_color_class', models.CharField(default='text-brand-700', help_text="Tailwind class like 'text-brand-700' or 'text-green-700'", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
