# Generated by Django 6.0.2 on 2026-02-28 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_destinationhighlight_pathwayhighlight_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLinkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Explore', 'Resources'", max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which categories appear (left to right)')),
            ],
            options={
                'verbose_name_plural': 'Footer Link Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(help_text="Can be a URL or a named URL pattern like '/about' or 'https://...'", max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='seo.footerlinkcategory')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
