# Generated by Django 6.0.2 on 2026-06-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0003_footerlinkcategory_footerlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localpage',
            name='destination',
            field=models.CharField(choices=[('UK', 'Orthopedic & Spine Care'), ('USA', 'Sports Rehabilitation'), ('AUS', 'Neurological & Stroke Recovery'), ('ALL', 'All Services')], default='ALL', max_length=3),
        ),
    ]
